gcloud dataproc clusters create baseline-cluster \
  --region=europe-west3 \
  --zone=europe-west3-a \
  --master-machine-type=n2-standard-4 \
  --master-boot-disk-size=100GB \
  --num-workers=3 \
  --worker-machine-type=n2-standard-4 \
  --worker-boot-disk-size=100GB \
  --image-version=2.2-debian12 \
  --optional-components=JUPYTER \
  --enable-component-gateway \
  --properties spark:spark.history.fs.logDirectory=gs://spark-memory-opt-bucket/spark-history